# Hexo Configuration
# Docs: https://hexo.io/docs/configuration.html

# 站点信息
title: Ante Liu
subtitle: Thanks For Watching！
description: 肄业，爱车，爱菇凉，爱民谣。墓志铭：Go and Null。
keywords: 理智,感性,AB型,codinginging
author: Ante Liu
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://noeverer.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
  pretty_urls:
    trailing_index: true
    trailing_html: true

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "scripts/**/*"

# 写作
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# 首页设置
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类 & 标签
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# 分页
per_page: 10
pagination_dir: page

# 扩展
theme: butterfly

# 预处理配置
ignore:
  - "../scripts/**/*"

# 部署配置（使用GitHub Actions，此处仅作为参考）
deploy:
  type: git
  repo: https://github.com/Noeverer/Noeverer.github.io.git
  branch: gh-pages

skip_render:
  - "scripts/**/*"
  - "**/*.py"
  - "**/*.sh"
  - "**/*.json"
